[reference]
url = "git@github.com:bezbac/myaku.git"

[metrics]

[metrics.loc]
collector = "total-loc"
frequency = "per-commit"

[metrics.diff]
collector = "total-diff-stat"
frequency = "per-commit"

[metrics.deps]
collector = "total-cargo-deps"
frequency = "per-commit"
