[reference]
url = "git@github.com:bezbac/myaku.git"

[metrics]

[metrics.loc]
collector = "total-loc"
frequency = "per-commit"

[metrics.diff]
collector = "total-diff-stat"
frequency = "per-commit"

[metrics.deps]
collector = "total-cargo-deps"
frequency = "per-commit"

[metrics.pattern-occurences]
collector = "pattern-occurences"
frequency = "per-commit"
pattern = "\\/\\/ TODO"
files = ["lib/src/collectors/**/*.rs"]

[metrics.total-file-count]
collector = "total-file-count"
frequency = "per-commit"

[metrics.changed-files-loc]
collector = "changed-files-loc"
frequency = "per-commit"
