[reference]
url = "git@github.com:bezbac/myaku.git"

[metrics]

[metrics.loc]
collector = "total-loc"
frequency = "per-commit"

[metrics.todos]
collector = "pattern-occurences"
frequency = "per-commit"
pattern = "\\/\\/ TODO"
